# Generated by Django 6.1.1 on 2026-09-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='register_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
